### PR TITLE
Have looked up ActiveModelSerializer opt into the new Serializer API

### PR DESCRIPTION
**Pull request by wecc**

### CODE REVIEW

**Comment by wecc** [comment]
@fivetanley Any ideas why this fail? Getting `ReferenceError: Can't find variable: DS`

**Comment by bmac** [comment]
https://github.com/ember-data/active-model-adapter/blob/master/bower.json#L7

The version of Ember Data in bower doesn't work with Ember beta or canary.

**Comment by bdvholmes** [comment]
Would this fix work if you're extending ActiveModelSerializer yourself?

**Comment by wecc** [comment]
@bdvholmes No, this is only for the default `ActiveModelSerializer` (that gets looked up from `ActiveModelAdapter`s `defaultSerializer`)

**Pull request merged**
