### PR TITLE
Set the ruby gem under maintenance mode (not the ember addon!)

### PR DESCRIPTION
**Pull request by dcyriller**
This ember addon is also published to rubygems under the name [active-model-adapter-source](https://rubygems.org/gems/active-model-adapter-source).

This PR proposes to change this first sentence tense: "This ember addon was published to rubygems.". From now on, only patch releases (probably on a 2.x branch) would get published to rubygems.

I don't think that integrating an ember addon through a ruby gem is recommended anymore. And [active_model_serializers](https://github.com/rails-api/active_model_serializers#status-of-ams) itself has gone under maintenance mode.

related issue in ember-data: https://github.com/emberjs/data/issues/7218
cc @igorT

### CODE REVIEW

**Comment by igorT** [comment]
This looks great. I wonder why Travis fails

**Comment by dcyriller** [comment]
Because it downloads and runs yarn in a Node 4 environnement 😢

**Comment by dcyriller** [comment]
@igorT https://github.com/ember-data/active-model-adapter/pull/134 should fix it :)

**Comment by igorT** [comment]
Wanna give it a quick rebase and I'll merge?

**Comment by dcyriller** [comment]
done ✅

**Comment by igorT** [comment]
@dcyriller  Seems like CI is now failing with a different error

**Comment by dcyriller** [comment]
Seems good now :)

**Pull request merged**
