### PR TITLE
Fix ember-inflector deprecations

### LINKED ISSUE #109: Deprecation warnings with recent ember-data
Hey, I'm sure you're already aware of this (and it's maybe even already fixed... I see there's been a bunch of activity updating dependencies recently, looking forward to it landing, thanks!), but I just updated from ember-data 2.12 to 2.16 and now I'm getting deprecation warnings from `active-model-adapter`'s code when starting my application:

```
DEPRECATION: Ember.String.pluralize() is deprecated. Please explicitly: import { pluralize } from 'ember-inflector'; [deprecation id: ember-inflector.globals]
DEPRECATION: Ember.String.singularize() is deprecated. Please explicitly: import { singularize } from 'ember-inflector'; [deprecation id: ember-inflector.globals]
```

### PR DESCRIPTION
**Pull request by rmachielse**
Fixes #109

### CODE REVIEW

**Comment by rmachielse** [comment]
@pangratz I think this is the change we need to fix the ember-inflector deprecations. I added the same version range that ember-data uses, therefore it doesn't cause any changes to `yarn.lock`. Do you agree it should explicitly depend on it?

Although the tests run fine on the `default` scenario, the job is failing with this error:
```
Cannot find module 'bower' from '/home/travis/build/ember-data/active-model-adapter/node_modules/ember-cli/bin'
```
Do you have any idea what that could be?

**Comment by rmachielse** [comment]
@pangratz the failing tests are related to ember-cli/ember-try#161, I prepended a commit to fix them.

**Comment by pangratz** [comment]
Sorry for the delay here @rmachielse.

Can you update this PR to use the latest version of ember inflector and add the updated `yarn.lock`  too? Also, once @Turbo87's #113 is merged, we can get rid of the updates to the ember try config and keep this PR updating ember-inflector only.

Thanks!

**Comment by Turbo87** [comment]
> I added the same version range that ember-data uses

@rmachielse `ember-data` is currently using `^2.0.0` (see https://github.com/emberjs/data/blob/ed4e45f7ca4a28a478293857442164e295eccf5b/package.json#L43)

**Comment by rmachielse** [comment]
@pangratz no problem, will do!

**Comment by rmachielse** [comment]
@pangratz @Turbo87 I have adapted, and tests are ✅

**Comment by pangratz** [comment]
Thanks @rmachielse for the quick response. This is ready for 🚀

**Comment by rmachielse** [comment]
@pangratz will you cut a release soon?

**Pull request merged**
