### PR TITLE
Remove unnecessary instance-initializer

### PR DESCRIPTION
**Pull request by tricknotes**
These registrations are enough by using initializer.
ref: https://github.com/ember-data/active-model-adapter/blob/2.0.1/app/initializers/active-model-adapter.js#L6-L10

### CODE REVIEW

**Comment by fivetanley** [comment]
I thought initializers were deprecated in 2.0+?

**Comment by bmac** [comment]
@fivetanley I believe initializers still exist in 2.0+. There API has just been change so they can't be used for looking up things.

**Comment by bmac** [comment]
Thanks @tricknotes

**Comment by tricknotes** [comment]
@fivetanley 
Sorry for my late response :<
@bmac says what I want to say.

Thanks a lot :D

**Pull request merged**
