### PR TITLE
Remove execute permission

### PR DESCRIPTION
**Pull request by tricknotes**
These files have no need to be executable.

### CODE REVIEW

**Comment by fivetanley** [comment]
@tricknotes hey sorry for the late replly. This is a good change, but unfortunately conflicts. Can you try rebasing master? Or if there's too many conflicts force push?

**Comment by tricknotes** [comment]
now rebased.

**Comment by tricknotes** [comment]
@fivetanley Is this OK?

**Comment by bmac** [comment]
Thanks @tricknotes.

**Pull request merged**
